In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.4 MB 4.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.4 MB 5.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.4 MB 5.5 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.4 MB 5.9 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.4 MB 6.0 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.4 MB 6.0 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.4 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.4 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 4.9 MB/s  0:00:02
Note: you ma

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
pip install pandas


   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 6.6 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.9 MB 4.5 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.9 MB 5.5 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 5.3 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.9 MB 5.1 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.9 MB 5.1 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 5.2 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.9 MB 5.2 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.9 MB 4.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.6 MB/s  0:00:02

   ---------------------------------------- 0/2 [tzdata]
   -------------------------------------

In [7]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np
import pandas as pd


In [9]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:", temperatures_w1)


Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [10]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)


Shape: (7,)
Data Type: float64
Number of Elements: 7


In [11]:
temperatures_f = (temperatures_w1 * 9/5) + 32
print("Temperatures in Fahrenheit:", temperatures_f)


Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [12]:
print("Maximum Temperature:", temperatures_w1.max())
print("Minimum Temperature:", temperatures_w1.min())
print("Mean Temperature:", temperatures_w1.mean())


Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [13]:
# First three days
print("First 3 days:", temperatures_w1[:3])

# Weekend (last two days)
print("Weekend temperatures:", temperatures_w1[-2:])

# Middle three days
print("Middle 3 days:", temperatures_w1[2:5])


First 3 days: [22.5 25.3 20.8]
Weekend temperatures: [24.8 21.9]
Middle 3 days: [20.8 23.4 26.1]


In [14]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("2D Temperature Array:\n", temperatures)


2D Temperature Array:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [15]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Elements:", temperatures.size)

# Temperatures for each week
print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])

# Weekend temperatures for both weeks
print("Weekend temperatures:\n", temperatures[:, -2:])


Shape: (2, 7)
Data Type: float64
Total Elements: 14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend temperatures:
 [[24.8 21.9]
 [22.8 20.1]]


In [16]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("Marks Series:\n", marks)


Marks Series:
 Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [18]:
#Indexing and Slicing
#1st Rank (Integer Index Position)

print("1st Rank Mark (by position):", marks.iloc[0])

1st Rank Mark (by position): 95


In [19]:
#Top 3 Ranks using loc

top3 = marks.loc[['Rank1', 'Rank2', 'Rank3']]
print("Top 3 Ranks Marks:")
print(top3)

Top 3 Ranks Marks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [20]:
#3rd Rank using iloc
print("3rd Rank Mark (using iloc):", marks.iloc[2])

3rd Rank Mark (using iloc): 89


In [21]:
#Boolean Mask (Marks > 90)
above_90 = marks[marks > 90]
print("Marks greater than 90:")
print(above_90)

Marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


In [22]:
#Manipulating Series Modify 1st Rank to 100
marks.loc['Rank1'] = 100
print("After Updating Rank1:")
print(marks)

After Updating Rank1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [23]:
#Remove Last Rank (Rank5)

marks = marks.drop('Rank5')
print("After Removing Rank5:")
print(marks)

After Removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [24]:
#Compute CGPA (Marks / 10)

cgpa = marks / 10
print("CGPA:")
print(cgpa)

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [25]:
#Creating Pandas DataFrame

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [26]:
#Data Exploration
# Head, Tail, Shape, Columns, Data Types

print("Head:")
print(transactions.head())

print("\nTail:")
print(transactions.tail())

print("\nShape:", transactions.shape)

print("\nColumn Names:")
print(transactions.columns)

print("\nData Types:")
print(transactions.dtypes)

print("\nInfo():")
print(transactions.info())

Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)

Column Names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

Data Types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

Info():
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           -----------

In [27]:
#Display Only 'ProductCategory' and 'Amount'

print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [28]:
#Retrieve Last 3 Columns (using iloc)

last_3_columns = transactions.iloc[:, -3:]
print("Last 3 Columns:")
print(last_3_columns)

Last 3 Columns:
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [29]:
#Filter: Region = 'North' AND Amount > 200

north_high_amount = transactions[
    (transactions['Region'] == 'North') & (transactions['Amount'] > 200)
]

print("North Region with Amount > 200:")
print(north_high_amount)

North Region with Amount > 200:
   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [30]:
#Value Counts for 'ProductCategory'

product_counts = transactions['ProductCategory'].value_counts()
print("Product Category Counts:")
print(product_counts)


Product Category Counts:
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [31]:
#Unique Values in 'Region'

unique_regions = transactions['Region'].unique()
print("Unique Regions:")
print(unique_regions)

Unique Regions:
<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str


In [32]:
#Group by 'Region' and Mean Amount

region_mean = transactions.groupby('Region')['Amount'].mean()
print("Mean Amount by Region:")
print(region_mean)

Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [33]:
#Manipulating the DataFrame
#Modify Amount for TransactionID = 102 to 165

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("After Updating TransactionID 102:")
print(transactions)

After Updating TransactionID 102:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [34]:
#Add New Column 'Discount' (10% of Amount)

transactions['Discount'] = transactions['Amount'] * 0.10
print("After Adding Discount Column:")
print(transactions)

After Adding Discount Column:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [35]:
#Remove Row with TransactionID = 109

transactions = transactions[transactions['TransactionID'] != 109]
print("After Removing TransactionID 109:")
print(transactions)

After Removing TransactionID 109:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [42]:
transactions.drop(columns='Discount', inplace=True)

KeyError: "['Discount'] not found in axis"